### PR TITLE
components/layout-wrapper: fix header width issues

### LINKED ISSUE #289: Horizontal scrollbar on mobile
When using a mobile device the website has a horizontal scrollbar and a bunch of empty space. This can sometimes make it tough to scroll down because scrolls can accidentally "catch" horizontally.

https://github.com/tailscale-dev/tailscale-dev/assets/303731/4bac0350-ae5f-468d-b76e-5651ce73d78a

### LINKED ISSUE #290: Search icon outside search bar
In the navigation, the search icon is sitting oddly outside the search bar, which feels like an accidental layout bug.

Screenshot 2023-08-15 at 09 05 16@2x

### PR DESCRIPTION
**Pull request by Xe**
While I was investigating #289 and #290, I found that there was an overall issue with header width. After adjusting all of the numbers to make the header look good on all our supported screen sizes, I think this should fix the root cause: invisible in Tailwind is not the same as hidden.

This should fix display on mobile phones as well as make the overall UX nicer on all browser widths.

Fixes #289
Fixes #290

### CODE REVIEW

File: components/layout-wrapper.tsx [hunk 1]
```diff
@@ -41,30 +41,54 @@ const LayoutWrapper = ({ children }: Props) => {
             </Link>
             <ul className="relative hidden pt-8 md:flex">
               {leftHeaderNavLinks.map((link) => (
-                <li key={link.title}>
+                <>
```
Comment (rosszurowski) [inline components/layout-wrapper.tsx:44]: I'm still seeing horizontal scrolling on [the search page](https://tailscale-htjugz306-tailscale.vercel.app/search?q=) at 796px wide.

File: components/layout-wrapper.tsx [hunk 2]
```diff
@@ -41,30 +41,54 @@ const LayoutWrapper = ({ children }: Props) => {
...
+                  </li>
+                </>
+              ))}
+              {noSearch && (
+                <li className="px-1.5 lg:px-2 xl:px-3 font-medium transition-colors duration-200 hover:text-gray-600">
+                  <Link href="/search">Search</Link>
+                </li>
+              )}
+            </ul>
+            {noSearch == false && (
```
Comment (rosszurowski) [inline components/layout-wrapper.tsx:65]: Rather than `noSearch &&` and `noSearch == false`, normally in React you'd express this with a ternary:

```
{noSearch ? (
  <>Option A</>
) : (
  <>Option B</>
)}
```

I'd recommend doing that here.

File: components/layout-wrapper.tsx [hunk 3]
```diff
@@ -41,30 +41,54 @@ const LayoutWrapper = ({ children }: Props) => {
...
               {leftHeaderNavLinks.map((link) => (
-                <li key={link.title}>
+                <>
+                  <li key={link.title}>
+                    <Link
+                      key={link.title}
+                      href={link.href}
+                      className="px-1.5 lg:px-2 xl:px-3 font-medium transition-colors duration-200 hover:text-gray-600"
+                    >
+                      <span>{link.title}</span>
```
Comment (rosszurowski) [inline components/layout-wrapper.tsx:51]: Currently the left and right menu items are right up against each other. I'm not sure if we want any space between the two sections to distinguish them?

Screenshot 2023-08-16 at 09 36 11@2x

**Review by rosszurowski — APPROVED** [review]
A few small comments, but I'll leave it to you to decide if/how you want to resolve em. Thanks for the fix!

**Comment by rosszurowski** [comment]
> I think this should fix the root cause: invisible in Tailwind is not the same as hidden.

One important distinction: `invisible` and `visible` in Tailwind refers to the `visibility: hidden` property in CSS, which doesn't affect layout, whereas `display: block` and `display: none` do. So this is more of a CSS thing than a Tailwind thing, though maybe the mapping isn't obvious.

File: components/layout-wrapper.tsx (hunk 3 above)
Comment (Xe) [reply components/layout-wrapper.tsx:51]: I think there's a bigger issue of too much stuff in the header in general. I did some number twiddling and this is the best compromise I can get at the moment. I filed #292 to track fixing this. we may need to redesign the navbar in general.

File: components/layout-wrapper.tsx (hunk 1 above)
Comment (Xe) [reply components/layout-wrapper.tsx:59]: Fixed with [48d9643](https://github.com/tailscale-dev/tailscale-dev/pull/291/commits/48d9643fb74e04b9a3c47e763e2020122994774e). It's a compromise though.
